# Generated by Django 5.2 on 2025-05-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('Primary Care Checkup', 'Primary Care Checkup'), ('Annual Physical Exam', 'Annual Physical Exam'), ('Fatigue', 'Fatigue'), ('Headache or Migraine', 'Headache or Migraine'), ('Dizziness', 'Dizziness'), ('Fever or Chills', 'Fever or Chills'), ('Cough or Cold', 'Cough or Cold'), ('Bug Bite', 'Bug Bite'), ('Rash Evaluation', 'Rash Evaluation'), ('Anxiety Counseling', 'Anxiety Counseling'), ('Stress Management', 'Stress Management'), ('Nutrition Counseling', 'Nutrition Counseling'), ('Sleep Disorder Management', 'Sleep Disorder Management')], default='Primary Care Checkup', max_length=256),
        ),
    ]
