# Generated by Django 5.2 on 2025-05-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('UserCanceled', 'UserCanceled'), ('ProviderCanceled', 'ProviderCanceled')], default='Scheduled', max_length=20),
        ),
    ]
